services:
  chiabill-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chiabill-backend
    ports:
      - "127.0.0.1:8080:8080"

    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

