spring.application.name=chia-bill

# ===============================
# SERVER PROFILE SWITCHER
# ===============================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

# ===============================
# DATASOURCE
# ===============================
JWT_SECRET=${JWT_SECRET}
google.client-id=${GOOGLE_CLIENT_ID}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE (Prod Defaults)
# ===============================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# LOGGING (Prod Defaults)
# ===============================
logging.level.root=INFO
logging.level.com.kaitohuy.chiabill=INFO

# cloudinary
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${API_KEY}
cloudinary.api-secret=${API_SECRET}

# ===============================
# MAIL SENDER
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FIREBASE
# ===============================
firebase.key.path=${FIREBASE_KEY_PATH:chiabill-firebase.json}