--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: expense_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expense_categories (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    icon character varying(255),
    name character varying(255) NOT NULL,
    trip_id bigint
);


--
-- Name: expense_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expense_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expense_splits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expense_splits (
    id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    is_settled boolean NOT NULL,
    percentage numeric(5,2),
    expense_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: expense_splits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expense_splits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_splits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expenses (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_uuid character varying(36),
    currency character varying(255),
    description character varying(255),
    exchange_rate numeric(15,6),
    expense_date timestamp(6) without time zone NOT NULL,
    is_from_fund boolean,
    receipt_url character varying(255),
    total_amount numeric(15,2) NOT NULL,
    category_id bigint,
    group_fund_id bigint,
    payer_id bigint NOT NULL,
    trip_id bigint NOT NULL
);


--
-- Name: expenses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_fund_contributions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_fund_contributions (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    amount numeric(15,2) NOT NULL,
    contribution_date timestamp(6) without time zone NOT NULL,
    is_confirmed boolean NOT NULL,
    notes character varying(255),
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    fund_id bigint NOT NULL,
    CONSTRAINT group_fund_contributions_type_check CHECK (((type)::text = ANY ((ARRAY['REQUIRED'::character varying, 'VOLUNTARY'::character varying])::text[])))
);


--
-- Name: group_fund_contributions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_fund_contributions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_fund_contributions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_funds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_funds (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    alert_threshold numeric(15,2),
    balance numeric(15,2) NOT NULL,
    currency character varying(255) NOT NULL,
    treasurer_id bigint NOT NULL,
    trip_id bigint NOT NULL
);


--
-- Name: group_funds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_funds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_funds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_read boolean,
    message text NOT NULL,
    reference_id bigint,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['EXPENSE_CREATED'::character varying, 'PAYMENT_REQUESTED'::character varying, 'PAYMENT_APPROVED'::character varying, 'TRIP_INVITE'::character varying, 'MEMBER_KICKED'::character varying, 'SYSTEM'::character varying, 'SETTLEMENT_CREATED'::character varying])::text[])))
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    amount numeric(38,2) NOT NULL,
    proof_url character varying(255),
    status character varying(255),
    from_user_id bigint NOT NULL,
    on_behalf_of_user_id bigint,
    to_user_id bigint NOT NULL,
    trip_id bigint NOT NULL,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_comment_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place_comment_likes (
    id bigint NOT NULL,
    comment_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: place_comment_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.place_comment_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_comment_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place_comments (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    content text NOT NULL,
    like_count integer NOT NULL,
    parent_id bigint,
    place_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: place_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.place_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place_images (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    album character varying(255) DEFAULT 'Khác'::character varying NOT NULL,
    image_url character varying(255) NOT NULL,
    place_id bigint NOT NULL,
    user_id bigint
);


--
-- Name: place_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.place_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place_reports (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    description text,
    report_type character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    place_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: place_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.place_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: places; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.places (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    category character varying(50),
    city character varying(255),
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    name character varying(255) NOT NULL,
    opening_hours character varying(100),
    summary text,
    ticket_prices text,
    creator_id bigint
);


--
-- Name: places_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.places ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.places_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trip_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_history (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    content text,
    created_at timestamp(6) without time zone,
    trip_id bigint NOT NULL,
    actor_id bigint NOT NULL
);


--
-- Name: trip_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trip_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trip_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trip_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_invitations (
    id character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    created_by bigint NOT NULL,
    trip_id bigint NOT NULL
);


--
-- Name: trip_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_members (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active boolean,
    joined_at timestamp(6) without time zone,
    role character varying(255),
    status character varying(255) DEFAULT 'ACTIVE'::character varying NOT NULL,
    trip_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT trip_members_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DISABLED'::character varying])::text[])))
);


--
-- Name: trip_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trip_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trip_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trips; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trips (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    cover_url character varying(255),
    currency character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    start_date timestamp(6) without time zone,
    total_budget numeric(15,2),
    created_by bigint NOT NULL
);


--
-- Name: trips_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_device_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_device_tokens (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_used_at timestamp(6) without time zone,
    platform character varying(255),
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_device_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_device_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_device_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    account_no character varying(255),
    allow_auto_add boolean DEFAULT true NOT NULL,
    allow_auto_approve_payment boolean DEFAULT true NOT NULL,
    avatar_url character varying(255),
    bank_id character varying(255),
    bank_qr_url character varying(255),
    email character varying(255),
    is_anonymous boolean NOT NULL,
    is_ghost boolean NOT NULL,
    name character varying(255) NOT NULL,
    payment_priority integer DEFAULT 1 NOT NULL,
    phone character varying(255),
    provider character varying(255),
    provider_id character varying(255),
    managed_by bigint
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expense_categories expense_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_categories
    ADD CONSTRAINT expense_categories_pkey PRIMARY KEY (id);


--
-- Name: expense_splits expense_splits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_splits
    ADD CONSTRAINT expense_splits_pkey PRIMARY KEY (id);


--
-- Name: expenses expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);


--
-- Name: group_fund_contributions group_fund_contributions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_fund_contributions
    ADD CONSTRAINT group_fund_contributions_pkey PRIMARY KEY (id);


--
-- Name: group_funds group_funds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_funds
    ADD CONSTRAINT group_funds_pkey PRIMARY KEY (id);


--
-- Name: place_comment_likes idx_place_comment_like_user_comment; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_comment_likes
    ADD CONSTRAINT idx_place_comment_like_user_comment UNIQUE (user_id, comment_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: place_comment_likes place_comment_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_comment_likes
    ADD CONSTRAINT place_comment_likes_pkey PRIMARY KEY (id);


--
-- Name: place_comments place_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_comments
    ADD CONSTRAINT place_comments_pkey PRIMARY KEY (id);


--
-- Name: place_images place_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_images
    ADD CONSTRAINT place_images_pkey PRIMARY KEY (id);


--
-- Name: place_reports place_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_reports
    ADD CONSTRAINT place_reports_pkey PRIMARY KEY (id);


--
-- Name: places places_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (id);


--
-- Name: trip_history trip_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_history
    ADD CONSTRAINT trip_history_pkey PRIMARY KEY (id);


--
-- Name: trip_invitations trip_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_invitations
    ADD CONSTRAINT trip_invitations_pkey PRIMARY KEY (id);


--
-- Name: trip_members trip_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_members
    ADD CONSTRAINT trip_members_pkey PRIMARY KEY (id);


--
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);


--
-- Name: group_funds uk2v41rvil5jykcqrtm40rsvf3e; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_funds
    ADD CONSTRAINT uk2v41rvil5jykcqrtm40rsvf3e UNIQUE (trip_id);


--
-- Name: expense_splits uk6d7okkopaxy9cprx202y5lxa0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_splits
    ADD CONSTRAINT uk6d7okkopaxy9cprx202y5lxa0 UNIQUE (expense_id, user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);


--
-- Name: trip_members ukhg97io4ecao95cff2peffr9u9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_members
    ADD CONSTRAINT ukhg97io4ecao95cff2peffr9u9 UNIQUE (trip_id, user_id);


--
-- Name: expenses ukp78v820u7sxvj2l64wjppxmbg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT ukp78v820u7sxvj2l64wjppxmbg UNIQUE (client_uuid);


--
-- Name: user_device_tokens user_device_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_device_tokens
    ADD CONSTRAINT user_device_tokens_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_expense_is_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expense_is_deleted ON public.expenses USING btree (is_deleted);


--
-- Name: idx_expense_payer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expense_payer ON public.expenses USING btree (payer_id);


--
-- Name: idx_expense_trip; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expense_trip ON public.expenses USING btree (trip_id);


--
-- Name: idx_expensesplit_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expensesplit_user ON public.expense_splits USING btree (user_id);


--
-- Name: idx_notification_is_read; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_is_read ON public.notifications USING btree (is_read);


--
-- Name: idx_notification_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_user ON public.notifications USING btree (user_id);


--
-- Name: idx_payment_from; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_from ON public.payments USING btree (from_user_id);


--
-- Name: idx_payment_is_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_is_deleted ON public.payments USING btree (is_deleted);


--
-- Name: idx_payment_to; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_to ON public.payments USING btree (to_user_id);


--
-- Name: idx_payment_trip; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_trip ON public.payments USING btree (trip_id);


--
-- Name: idx_place_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_category ON public.places USING btree (category);


--
-- Name: idx_place_city; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_city ON public.places USING btree (city);


--
-- Name: idx_place_comment_is_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_comment_is_deleted ON public.place_comments USING btree (is_deleted);


--
-- Name: idx_place_comment_place_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_comment_place_id ON public.place_comments USING btree (place_id);


--
-- Name: idx_place_image_is_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_image_is_deleted ON public.place_images USING btree (is_deleted);


--
-- Name: idx_place_image_place_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_image_place_id ON public.place_images USING btree (place_id);


--
-- Name: idx_place_is_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_is_deleted ON public.places USING btree (is_deleted);


--
-- Name: idx_place_report_is_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_report_is_deleted ON public.place_reports USING btree (is_deleted);


--
-- Name: idx_place_report_place_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_report_place_id ON public.place_reports USING btree (place_id);


--
-- Name: idx_trip_is_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trip_is_deleted ON public.trips USING btree (is_deleted);


--
-- Name: idx_tripmember_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tripmember_active ON public.trip_members USING btree (is_active);


--
-- Name: idx_tripmember_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tripmember_status ON public.trip_members USING btree (status);


--
-- Name: idx_tripmember_trip; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tripmember_trip ON public.trip_members USING btree (trip_id);


--
-- Name: idx_tripmember_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tripmember_user ON public.trip_members USING btree (user_id);


--
-- Name: place_comments fk1907htn9onb3h4rpkh1jskfxe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_comments
    ADD CONSTRAINT fk1907htn9onb3h4rpkh1jskfxe FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: place_comment_likes fk3kayu2ajgv0giubekky306hyw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_comment_likes
    ADD CONSTRAINT fk3kayu2ajgv0giubekky306hyw FOREIGN KEY (comment_id) REFERENCES public.place_comments(id);


--
-- Name: place_reports fk51sfx6jqx1t5im84sga0xypfh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_reports
    ADD CONSTRAINT fk51sfx6jqx1t5im84sga0xypfh FOREIGN KEY (place_id) REFERENCES public.places(id);


--
-- Name: place_comment_likes fk5vlgs1s1xto0bmayr8673h1r2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_comment_likes
    ADD CONSTRAINT fk5vlgs1s1xto0bmayr8673h1r2 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: place_reports fk5wo84u5ghbesckf4bxc35krnx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_reports
    ADD CONSTRAINT fk5wo84u5ghbesckf4bxc35krnx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: payments fk5ygpkypx3434pgm7c2dlclfxw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk5ygpkypx3434pgm7c2dlclfxw FOREIGN KEY (to_user_id) REFERENCES public.users(id);


--
-- Name: expenses fk5yxjoxu59w6oehxws2gtrer5k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fk5yxjoxu59w6oehxws2gtrer5k FOREIGN KEY (group_fund_id) REFERENCES public.group_funds(id);


--
-- Name: trip_members fk652lcpk0gdigjfm28bhgu24y2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_members
    ADD CONSTRAINT fk652lcpk0gdigjfm28bhgu24y2 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: payments fk74waay8m8qk4vdxse9h88gg2w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk74waay8m8qk4vdxse9h88gg2w FOREIGN KEY (from_user_id) REFERENCES public.users(id);


--
-- Name: trip_invitations fk7fogh4awsdmv466walfbyclh0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_invitations
    ADD CONSTRAINT fk7fogh4awsdmv466walfbyclh0 FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: places fk8sa7m2uy01wbscklegnnpcl3y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT fk8sa7m2uy01wbscklegnnpcl3y FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: place_comments fk9gtx2cxplxjc9ef3l63ho39n4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_comments
    ADD CONSTRAINT fk9gtx2cxplxjc9ef3l63ho39n4 FOREIGN KEY (place_id) REFERENCES public.places(id);


--
-- Name: expenses fk9twvm79qw1voae3xgtn1xq5y9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fk9twvm79qw1voae3xgtn1xq5y9 FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: trips fkc4x3abgpcmxs8xcr9f238fpby; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkc4x3abgpcmxs8xcr9f238fpby FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: group_fund_contributions fkd144i83rdd1bp5t0hwjg5l8kn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_fund_contributions
    ADD CONSTRAINT fkd144i83rdd1bp5t0hwjg5l8kn FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_device_tokens fkevk16cemgy1bwx5s0d6oa8x41; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_device_tokens
    ADD CONSTRAINT fkevk16cemgy1bwx5s0d6oa8x41 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: place_images fkfaf8mjrs1svk7fgqxufaajmiq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_images
    ADD CONSTRAINT fkfaf8mjrs1svk7fgqxufaajmiq FOREIGN KEY (place_id) REFERENCES public.places(id);


--
-- Name: trip_invitations fkfiqptshmtmolwrcvdc2d2k2af; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_invitations
    ADD CONSTRAINT fkfiqptshmtmolwrcvdc2d2k2af FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: group_funds fkg6wdo2b8sc34vvtctjy4qh8hn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_funds
    ADD CONSTRAINT fkg6wdo2b8sc34vvtctjy4qh8hn FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: expenses fkg7aulw52en8nct0mjq8uut03q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkg7aulw52en8nct0mjq8uut03q FOREIGN KEY (category_id) REFERENCES public.expense_categories(id);


--
-- Name: group_funds fkho0hxi65cmpw8q62ygfchqsir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_funds
    ADD CONSTRAINT fkho0hxi65cmpw8q62ygfchqsir FOREIGN KEY (treasurer_id) REFERENCES public.users(id);


--
-- Name: payments fkk1k4eds595iabbddfl58901jm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkk1k4eds595iabbddfl58901jm FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: place_images fkk8xda5f39ygq4shbirv49l9hq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_images
    ADD CONSTRAINT fkk8xda5f39ygq4shbirv49l9hq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: trip_members fklrwxwvuaj3iddljvck3c3gtqr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_members
    ADD CONSTRAINT fklrwxwvuaj3iddljvck3c3gtqr FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: expense_splits fknikv7drxxkj9x862du3r4ruam; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_splits
    ADD CONSTRAINT fknikv7drxxkj9x862du3r4ruam FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: payments fkow48nq9254c5axxar13b5kvhf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkow48nq9254c5axxar13b5kvhf FOREIGN KEY (on_behalf_of_user_id) REFERENCES public.users(id);


--
-- Name: expenses fkp2j9bd9avgsllmn3q7ssmdku; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkp2j9bd9avgsllmn3q7ssmdku FOREIGN KEY (payer_id) REFERENCES public.users(id);


--
-- Name: users fkp3vea0h7g2pdskcgy40w46n4d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp3vea0h7g2pdskcgy40w46n4d FOREIGN KEY (managed_by) REFERENCES public.users(id);


--
-- Name: trip_history fkpnd0hoed6kbnqhxk8mbe52kg7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_history
    ADD CONSTRAINT fkpnd0hoed6kbnqhxk8mbe52kg7 FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: expense_splits fkqigr3qe91wgifpl6mak0xcdso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_splits
    ADD CONSTRAINT fkqigr3qe91wgifpl6mak0xcdso FOREIGN KEY (expense_id) REFERENCES public.expenses(id);


--
-- Name: group_fund_contributions fksgd9lwtylh6w9d9hu30q4nsdh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_fund_contributions
    ADD CONSTRAINT fksgd9lwtylh6w9d9hu30q4nsdh FOREIGN KEY (fund_id) REFERENCES public.group_funds(id);


--
-- Name: expense_categories fkt8qbd7d79ptf544ao5q4s2gwh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_categories
    ADD CONSTRAINT fkt8qbd7d79ptf544ao5q4s2gwh FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- PostgreSQL database dump complete
--

