-- 1. Add role column to users table
ALTER TABLE public.users ADD COLUMN role varchar(50) DEFAULT 'USER' NOT NULL;

-- 2. Create system_feedback table
CREATE TABLE public.system_feedback (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id bigint NOT NULL,
    content text NOT NULL
);

ALTER TABLE public.system_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.system_feedback
    ADD CONSTRAINT system_feedback_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.system_feedback
    ADD CONSTRAINT fk_system_feedback_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
